//go:build ignore

package main

import (
	"log"
	"os"
	"strconv"
	"text/template"
)

type TemplateData struct {
	BlockGroups []BlockGroup
	HeadGroup   BlockGroup
	TailGroup   BlockGroup
}

type BlockGroup struct {
	Blocks    int
	Next      string
	Loop      bool
	Suffix    string
	BlockRegs []RegPair
}

type RegPair struct {
	Counter int
	Dest    int
}

type AESPath struct {
	Mode        string
	RoundGroups []RoundGroup
}

type RoundGroup struct {
	KeyRegs []int
	WithMix bool
}

const templateSrc = `// Code generated by ctr_arm64_gen.go. DO NOT EDIT.

//go:build !purego

#include "textflag.h"

#define HEAD_SKIP R8
#define NR R9
#define XK R10
#define DST R11
#define SRC R12
#define BLOCKS R13
#define HEAD_LEN R14
#define TAIL_LEN R15
#define IV_LOW_LE R16
#define IV_HIGH_LE R17
#define IV_LOW_BE R19
#define IV_HIGH_BE R20
#define TMP0 R21
#define TMP1 R22
#define TMP2 R23

// func ctrAsm(nr int, xk *[60]uint32, dst *byte, src *byte, headSkip int, headLen int, blocks int, tailLen int, ivlo uint64, ivhi uint64)
TEXT ·ctrAsm(SB), NOSPLIT, $0-80
	MOVD nr+0(FP), NR
	MOVD xk+8(FP), XK
	MOVD dst+16(FP), DST
	MOVD src+24(FP), SRC
	MOVD headSkip+32(FP), HEAD_SKIP
	MOVD headLen+40(FP), HEAD_LEN
	MOVD blocks+48(FP), BLOCKS
	MOVD tailLen+56(FP), TAIL_LEN
	MOVD ivlo+64(FP), IV_LOW_LE
	MOVD ivhi+72(FP), IV_HIGH_LE

{{ template "LoadKeys" }}

{{ template "Head" .HeadGroup }}

{{ range $group := .BlockGroups }}
	{{ template "Process" $group }}
{{ end }}

{{ template "Tail" .TailGroup }}

done:
	RET

{{ define "LoadKeys" }}
	CMP  $12, NR
	BLT  load128
	BEQ  load192

	load256:
		VLD1.P 32(XK), [V8.B16, V9.B16]

	load192:
		VLD1.P 32(XK), [V10.B16, V11.B16]

	load128:
		VLD1.P 64(XK), [V12.B16, V13.B16, V14.B16, V15.B16]
		VLD1.P 64(XK), [V16.B16, V17.B16, V18.B16, V19.B16]
		VLD1.P 48(XK), [V20.B16, V21.B16, V22.B16]
{{ end }}

{{ define "Process" }}
	process{{ .Blocks }}:
	{{ if eq .Blocks 1 }}
		CBZ  BLOCKS, tail
	{{ else }}
		CMP  ${{ .Blocks }}, BLOCKS
		BLT  {{ .Next }}
	{{ end }}

	{{ template "LoadFull" . }}

	{{ template "CountersAndRounds" . }}

	{{ template "XorAndStore" . }}

	SUBS ${{ .Blocks }}, BLOCKS
	{{ if .Loop }}
		B    process{{ .Blocks }}
	{{ end }}
{{ end }}

{{ define "CountersAndRounds" }}
	{{ $group := . }}
	{{ $suffix := .Suffix }}
	{{ range $pair := $group.BlockRegs }}
		MOVD IV_LOW_LE, IV_LOW_BE
		MOVD IV_HIGH_LE, IV_HIGH_BE
		REV  IV_LOW_BE, IV_LOW_BE
		REV  IV_HIGH_BE, IV_HIGH_BE
		VMOV IV_HIGH_BE, V{{ $pair.Counter }}.D[0]
		VMOV IV_LOW_BE, V{{ $pair.Counter }}.D[1]
		ADDS $1, IV_LOW_LE
		ADC  $0, IV_HIGH_LE
	{{ end }}

	CMP  $12, NR
	BLT  Lenc128_{{ $suffix }}
	BEQ  Lenc192_{{ $suffix }}

	{{ range $path := aesPaths }}
	Lenc{{ $path.Mode }}_{{ $suffix }}:
	{{ range $round := $path.RoundGroups }}
	{{ range $key := $round.KeyRegs }}
	{{ range $pair := $group.BlockRegs -}}
		AESE V{{ $key }}.B16, V{{ $pair.Counter }}.B16
		{{- if $round.WithMix }}
			AESMC V{{ $pair.Counter }}.B16, V{{ $pair.Counter }}.B16
		{{- end }}
	{{ end }}
	{{ end }}
	{{ end }}
	{{ end }}
{{ end }}

{{ define "LoadFull" }}
	{{ range $pair := .BlockRegs -}}
		VLD1.P 16(SRC), [V{{ $pair.Dest }}.B16]
	{{ end }}
{{ end }}

{{ define "FinalXor" }}
	{{ range $pair := .BlockRegs -}}
		VEOR V{{ $pair.Counter }}.B16, V22.B16, V{{ $pair.Counter }}.B16
	{{ end }}
{{ end }}

{{ define "XorAndStore" }}
	{{ range $pair := .BlockRegs -}}
		VEOR V{{ $pair.Counter }}.B16, V22.B16, V{{ $pair.Counter }}.B16
		VEOR V{{ $pair.Dest }}.B16, V{{ $pair.Counter }}.B16, V{{ $pair.Dest }}.B16
		VST1.P [V{{ $pair.Dest }}.B16], 16(DST)
	{{ end }}
{{ end }}

{{ define "Head" }}
	head:
		CBZ HEAD_LEN, head_done

		{{ template "CountersAndRounds" . }}
		{{ template "FinalXor" . }}

		MOVD HEAD_SKIP, TMP0
		CBZ TMP0, head_skip_done

	head_skip_loop:
		VEXT $1, V0.B16, V0.B16, V0.B16
		SUBS $1, TMP0
		BNE  head_skip_loop

	head_skip_done:
		MOVD HEAD_LEN, TMP0

	{{ template "ByteLoop" "head" }}

		CBZ BLOCKS, tail
{{ end }}

{{ define "Tail" }}
	tail:
		CBZ TAIL_LEN, done

		{{ template "CountersAndRounds" . }}
		{{ template "FinalXor" . }}

		MOVD TAIL_LEN, TMP0

	{{ template "ByteLoop" "tail" }}
{{ end }}

{{ define "ByteLoop" }}
		CBZ TMP0, {{ . }}_done
	{{ . }}_loop:
		MOVBU.P 1(SRC), TMP1
		VMOV V0.D[0], TMP2
		EOR  TMP2, TMP1
		MOVB.P TMP1, 1(DST)

		VEXT $1, V0.B16, V0.B16, V0.B16

		SUBS $1, TMP0
		BNE  {{ . }}_loop
	{{ . }}_done:
{{ end }}
`

func main() {
	tmpl := template.Must(template.New("ctrArm64").
		Funcs(template.FuncMap{
			"aesPaths": aesPaths,
		}).
		Parse(templateSrc))

	data := TemplateData{
		BlockGroups: blockGroups(),
		HeadGroup:   singleGroup("head"),
		TailGroup:   singleGroup("tail"),
	}

	if err := tmpl.Execute(os.Stdout, data); err != nil {
		log.Fatal(err)
	}
}

func blockGroups() []BlockGroup {
	specs := []struct {
		Blocks int
		Next   string
		Loop   bool
	}{
		{Blocks: 8, Next: "process4", Loop: true},
		{Blocks: 4, Next: "process2"},
		{Blocks: 2, Next: "process1"},
		{Blocks: 1, Next: ""},
	}
	groups := make([]BlockGroup, len(specs))
	for idx, spec := range specs {
		blockRegs := make([]RegPair, spec.Blocks)
		for i := 0; i < spec.Blocks; i++ {
			blockRegs[i] = RegPair{
				Counter: i,
				Dest:    23 + i,
			}
		}
		groups[idx] = BlockGroup{
			Blocks:    spec.Blocks,
			Next:      spec.Next,
			Loop:      spec.Loop,
			Suffix:    strconv.Itoa(spec.Blocks),
			BlockRegs: blockRegs,
		}
	}
	return groups
}

func singleGroup(suffix string) BlockGroup {
	return BlockGroup{
		Blocks: 1,
		Suffix: suffix,
		BlockRegs: []RegPair{
			{Counter: 0, Dest: 23},
		},
	}
}

func aesPaths() []AESPath {
	return []AESPath{
		{
			Mode: "256",
			RoundGroups: []RoundGroup{
				{KeyRegs: []int{8, 9}, WithMix: true},
			},
		},
		{
			Mode: "192",
			RoundGroups: []RoundGroup{
				{KeyRegs: []int{10, 11}, WithMix: true},
			},
		},
		{
			Mode: "128",
			RoundGroups: []RoundGroup{
				{
					KeyRegs: []int{
						12, 13, 14, 15, 16, 17, 18, 19, 20,
					},
					WithMix: true,
				},
				{KeyRegs: []int{21}, WithMix: false},
			},
		},
	}
}
